vich_uploader:
    db_driver: orm

    mappings:
        apropos_image:
            uri_prefix: build/images
            upload_destination: '%kernel.project_dir%/public/build/images'
            namer: Vich\UploaderBundle\Naming\UniqidNamer


    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
